name: ShutdownPlugin
main: com.example.shutdown.ShutdownPlugin
version: 1.0
description: 通过密码验证关闭服务器的插件
author: YourName

commands:
  wstop:
    description: 输入密码关闭服务器
    usage: /wstop <密码>
    permission: shutdownplugin.use
    permission-message: 你没有权限使用此命令
